[package]
name = "parse_the_parcel"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
clap-num = "1.2.0"
config = { version = "0.15.13", features = ["json"] }
serde = "1.0.219"
